base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: Français
    enabled: true
    locale: fr_CH
    base: /
    websiteTitle: ''
    navigationTitle: Français
    flag: fr
    languageId: 0
  -
    title: Deutsch
    enabled: true
    locale: de_CH
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 1
websiteTitle: Burkinamis
