#!/bin/bash
# Usage:
# ddev db

# Exit the script on error and unbound variable
set -eu

# Load common configuration
source "/mnt/ddev_config/commands/config.sh"

ssh ${SSH_HOST} -p ${SSH_PORT} "cat ${CREDENTIALS_PATH}"
