#!/usr/bin/env bash
# Usage:
# ddev db

# Exit the script on error and unbound variable
set -eu

# Load common configuration
source "/mnt/ddev_config/commands/config.sh"

echo "Dump remote database..."
ssh "${SSH_HOST}" -p "${SSH_PORT}" "mysqldump -u ${DB_USER} -p'${DB_PASSWORD}' -P ${DB_PORT} -h ${DB_HOST} -c ${DB_NAME} | gzip > /tmp/${DB_NAME}.sql.gz"

echo "Fetching dump..."
scp -P "${SSH_PORT}" "${SSH_HOST}":/tmp/"${DB_NAME}".sql.gz /tmp/"${DB_NAME}".sql.gz

echo "Extracting file..."
gzip -d /tmp/"${DB_NAME}".sql.gz

echo "Reset database..."
mysql -u db -pdb -e "DROP DATABASE IF EXISTS db; CREATE DATABASE db;"

echo "Import dump..."
mysql -u db -pdb db < /tmp/"${DB_NAME}".sql

echo "Fine tunes database..."
#mysql -u db -pdb -e "UPDATE sys_domain SET domainName = REPLACE(domainName, 'burkinamis.org', 'burkinamis.lan');" db
mysql -u db -pdb -e "UPDATE sys_template SET title = REPLACE(title, 'burkinamis.org', 'burkinamis.lan');" db
mysql -u db -pdb -e "UPDATE sys_template SET config = REPLACE(config, 'burkinamis.org', 'burkinamis.lan');" db
mysql -u db -pdb -e "UPDATE sys_template SET constants = REPLACE(constants, 'burkinamis.org', 'burkinamis.lan');" db
mysql -u db -pdb -e "UPDATE pages SET title = REPLACE(title, 'burkinamis.org', 'burkinamis.lan');" db

echo "Clean up environment..."
ssh "${SSH_HOST}" -p "${SSH_PORT}"  "rm /tmp/${DB_NAME}.sql.gz"
rm -f /tmp/"${DB_NAME}".sql

echo "Update schema..."
./vendor/bin/typo3 database:updateschema
