#!/usr/bin/env bash
## Description: Symlink current context
## Usage: symlink
## Example: "ddev symlink"

# Exit the script on error and unbound variable
set -eu

rm /var/www/html/config/context/current
ln -s Development/ddev /var/www/html/config/context/current